steps:
  # Step 1: Build the container image using Cloud Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south2-docker.pkg.dev/deft-manifest-450908-e3/myimage/myimage:$SHORT_SHA'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south2-docker.pkg.dev/deft-manifest-450908-e3/myimage/myimage:$SHORT_SHA'

images:
  - 'asia-south2-docker.pkg.dev/deft-manifest-450908-e3/myimage/myimage:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY  # Store logs in Cloud Logging
