steps:
  # Step 1: Build the container image using Cloud Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/dev-country-451703-v5/demoartifcat/democloudengine:$SHORT_SHA'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/dev-country-451703-v5/demoartifcat/democloudengine:$SHORT_SHA'
  
  # Step 3: Authenticate with GKE (NEW STEP)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'
      - '--region=us-central1'
      
  # Step 3: Update the Kubernetes deployment with the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/deployment-1'
      - 'nginx-1=us-central1-docker.pkg.dev/dev-country-451703-v5/demoartifcat/democloudengine:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
images:
  - 'us-central1-docker.pkg.dev/dev-country-451703-v5/demoartifcat/democloudengine:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY  # Store logs in Cloud Logging
